on:
  workflow_dispatch:

jobs:
  delete_all:
    runs-on: ubuntu-latest
    name: Delete Releases & Tags
    steps:
    - uses: actions/checkout@master
    - name: Todo Deleto Cuz
      id: del_all
      uses: actions/github-script@v7
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const releases = await github.rest.repos.listReleases({
            owner: owner,
            repo: repo,
          });
          
          if (releases && releases.data && releases.data.id) {
            for (let rel in releases) {
              await github.rest.repos.deleteRelease({
                owner: owner,
                repo: repo,
                release_id: rel.data.id,
              });
              console.log(`Deleted release with ID ${rel.data.id}`);
            }
          } else {
            console.log("No latest release found or failed to retrieve it.");
          }
