on:
  workflow_dispatch:

jobs:
  delete_all:
    runs-on: ubuntu-latest
    name: Delete Releases & Tags
    steps:
    - uses: actions/checkout@master
    - name: install github-remove
      id: github_remove
      run: |
        npm install --global github-remove-all-releases
        github-remove-all-releases ${{ github.repository_owner }} ${{ github.event.repository.name }}
