on:
  workflow_dispatch:

jobs:
  delete_all:
    runs-on: ubuntu-latest
    name: Delete Releases & Tags
    steps:
    - uses: actions/checkout@master
    - name: github-remove-all
      id: github_remove
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install --global github-remove-all-releases
        github-remove-all-releases ${{ github.repository_owner }} ${{ github.event.repository.name }} -t ${{ secrets.GITHUB_TOKEN }}
