on:
  workflow_dispatch:

jobs:
  delete_all:
    runs-on: ubuntu-latest
    name: Delete Releases & Tags
    steps:
    - uses: actions/checkout@master
    - name: Todo Deleto Cuz
      id: del_all
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const releases = await github.rest.repos.listReleases({
            owner: owner,
            repo: repo,
          });
    
          for release in releases {
            await github.rest.repos.deleteRelease({
              owner: owner,
              repo: repo,
              release_id: release.id,
            });
            console.log(`Deleted release with ID ${release.id}`);
          }
