on:
  workflow_dispatch:

jobs:
  delete_all:
    runs-on: ubuntu-latest
    name: Delete Releases & Tags
    steps:
    - uses: actions/checkout@master
    - name: Todo Deleto Cuz
      id: del_all
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release list \
          | awk -F '\t' '{print $3}' \ 
          | while read -r line; do
          gh release delete -y "$line" --cleanup-tag
        done
      shell: bash
